### ISSUE TITLE
checkpoint()   error

### ISSUE THREAD

**Issue by sunnyboy00** [LouisScorpio/datamining#3]
module_file = tf.train.latest_checkpoint()    

TypeError: latest_checkpoint() takes at least 1 argument (0 given)

**Comment by LouisScorpio** [comment]
@sunnyboy00 
需要输入路径参数。你模型存放的路径

**Comment by sunnyboy00** [comment]
@LouisScorpio 
谢谢，此问题已经搞定
另外
for i in range(2000):
导致最后200个模型未保存，建议更改为
for i in range(2001):

**Comment by LouisScorpio** [comment]
@sunnyboy00 好的，谢谢提醒
