### ISSUE TITLE
关于stock_predict_2.py

### ISSUE THREAD

**Issue by JianghaoPi** [LouisScorpio/datamining#4]
请问po主用的python3.几以及相应的tensorflow版本是多少？我这里会报错
AttributeError: module 'tensorflow.python.ops.nn' has no attribute 'rnn_cell'
stackoverflow上说是因为我的tensorflow版本太新，改动比较大

**Comment by JianghaoPi** [comment]
另外，predict1的dataset百度云好像失效了，能不能补一个啊？最近在做这块，很希望能跟着学一学，不胜感激

**Comment by LouisScorpio** [comment]
@JianghaoPi 是tensorflow0.12
多谢提醒，已经把dataset1传到github上了

**Comment by zxhui1986** [comment]
训练模型 及以上执行没问题，但是在预测模型之后，执行就报错了。报错信息如下：<tensorflow.contrib.rnn.python.ops.core_rnn_cell_impl.BasicLSTMCell object at 0x1232e3250>
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-9-27f781980483> in <module>()
     24         #plt.show()
     25 
---> 26 prediction()

<ipython-input-9-27f781980483> in prediction(batch_size, time_step, train_begin, train_end)
      4     #Y=tf.placeholder(tf.float32, shape=[None,time_step,output_size])
      5     mean,std,test_x,test_y=get_test_data(time_step)
----> 6     pred,_=lstm(X)
      7     #saver=tf.train.Saver(tf.global_variables())
      8     with tf.Session() as sess:

<ipython-input-5-5a82fdc53752> in lstm(X)
     18 
     19     init_state=cell.zero_state(batch_size,dtype=tf.float32)
---> 20     output_rnn,final_states=tf.nn.dynamic_rnn(cell, input_rnn,initial_state=init_state, dtype=tf.float32)  #output_rnn是记录lstm每个输出节点的结果，final_states是最后一个cell的结果
     21     output=tf.reshape(output_rnn,[-1,rnn_unit]) #作为输出层的输入
     22     w_out=weights['out']

/Users/xiaohuizhang/Documents/software/python/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/rnn.pyc in dynamic_rnn(cell, inputs, sequence_length, initial_state, dtype, parallel_iterations, swap_memory, time_major, scope)
    544         swap_memory=swap_memory,
    545         sequence_length=sequence_length,
--> 546         dtype=dtype)
    547 
    548     # Outputs of _dynamic_rnn_loop are always shaped [time, batch, depth].

/Users/xiaohuizhang/Documents/software/python/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/rnn.pyc in _dynamic_rnn_loop(cell, inputs, initial_state, parallel_iterations, swap_memory, sequence_length, dtype)
    711       loop_vars=(time, output_ta, state),
    712       parallel_iterations=parallel_iterations,
--> 713       swap_memory=swap_memory)
    714 
    715   # Unpack final output if not using output tuples.

/Users/xiaohuizhang/Documents/software/python/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.pyc in while_loop(cond, body, loop_vars, shape_invariants, parallel_iterations, back_prop, swap_memory, name)
   2603     context = WhileContext(parallel_iterations, back_prop, swap_memory, name)
   2604     ops.add_to_collection(ops.GraphKeys.WHILE_CONTEXT, context)
-> 2605     result = context.BuildLoop(cond, body, loop_vars, shape_invariants)
   2606     return result
   2607 

/Users/xiaohuizhang/Documents/software/python/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.pyc in BuildLoop(self, pred, body, loop_vars, shape_invariants)
   2436       self.Enter()
   2437       original_body_result, exit_vars = self._BuildLoop(
-> 2438           pred, body, original_loop_vars, loop_vars, shape_invariants)
   2439     finally:
   2440       self.Exit()

/Users/xiaohuizhang/Documents/software/python/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.pyc in _BuildLoop(self, pred, body, original_loop_vars, loop_vars, shape_invariants)
   2386         structure=original_loop_vars,
   2387         flat_sequence=vars_for_body_with_tensor_arrays)
-> 2388     body_result = body(*packed_vars_for_body)
   2389     if not nest.is_sequence(body_result):
   2390       body_result = [body_result]

/Users/xiaohuizhang/Documents/software/python/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/rnn.pyc in _time_step(time, output_ta_t, state)
    696           skip_conditionals=True)
    697     else:
--> 698       (output, new_state) = call_cell()
    699 
    700     # Pack state if using state tuples

/Users/xiaohuizhang/Documents/software/python/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/rnn.pyc in <lambda>()
    682 
    683     input_t = nest.pack_sequence_as(structure=inputs, flat_sequence=input_t)
--> 684     call_cell = lambda: cell(input_t, state)
    685 
    686     if sequence_length is not None:

/Users/xiaohuizhang/Documents/software/python/anaconda/lib/python2.7/site-packages/tensorflow/contrib/rnn/python/ops/core_rnn_cell_impl.pyc in __call__(self, inputs, state, scope)
    177       else:
    178         c, h = array_ops.split(value=state, num_or_size_splits=2, axis=1)
--> 179       concat = _linear([inputs, h], 4 * self._num_units, True, scope=scope)
    180 
    181       # i = input_gate, j = new_input, f = forget_gate, o = output_gate

/Users/xiaohuizhang/Documents/software/python/anaconda/lib/python2.7/site-packages/tensorflow/contrib/rnn/python/ops/core_rnn_cell_impl.pyc in _linear(args, output_size, bias, bias_start, scope)
    745   with vs.variable_scope(scope) as outer_scope:
    746     weights = vs.get_variable(
--> 747         "weights", [total_arg_size, output_size], dtype=dtype)
    748     if len(args) == 1:
    749       res = math_ops.matmul(args[0], weights)

/Users/xiaohuizhang/Documents/software/python/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.pyc in get_variable(name, shape, dtype, initializer, regularizer, trainable, collections, caching_device, partitioner, validate_shape, custom_getter)
    986       collections=collections, caching_device=caching_device,
    987       partitioner=partitioner, validate_shape=validate_shape,
--> 988       custom_getter=custom_getter)
    989 get_variable_or_local_docstring = (
    990     """%s

/Users/xiaohuizhang/Documents/software/python/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.pyc in get_variable(self, var_store, name, shape, dtype, initializer, regularizer, trainable, collections, caching_device, partitioner, validate_shape, custom_getter)
    888           collections=collections, caching_device=caching_device,
    889           partitioner=partitioner, validate_shape=validate_shape,
--> 890           custom_getter=custom_getter)
    891 
    892   def _get_partitioned_variable(self,

/Users/xiaohuizhang/Documents/software/python/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.pyc in get_variable(self, name, shape, dtype, initializer, regularizer, reuse, trainable, collections, caching_device, partitioner, validate_shape, custom_getter)
    346           reuse=reuse, trainable=trainable, collections=collections,
    347           caching_device=caching_device, partitioner=partitioner,
--> 348           validate_shape=validate_shape)
    349 
    350   def _get_partitioned_variable(

/Users/xiaohuizhang/Documents/software/python/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.pyc in _true_getter(name, shape, dtype, initializer, regularizer, reuse, trainable, collections, caching_device, partitioner, validate_shape)
    331           initializer=initializer, regularizer=regularizer, reuse=reuse,
    332           trainable=trainable, collections=collections,
--> 333           caching_device=caching_device, validate_shape=validate_shape)
    334 
    335     if custom_getter is not None:

/Users/xiaohuizhang/Documents/software/python/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.pyc in _get_single_variable(self, name, shape, dtype, initializer, regularizer, partition_info, reuse, trainable, collections, caching_device, validate_shape)
    637                          u" Did you mean to set reuse=True in VarScope? "
    638                          u"Originally defined at:\n\n%s" % (
--> 639                              name, u"".join(traceback.format_list(tb))))
    640       found_var = self._vars[name]
    641       if not shape.is_compatible_with(found_var.get_shape()):

<type 'str'>: (<type 'exceptions.UnicodeEncodeError'>, UnicodeEncodeError('ascii', u'Variable rnn/basic_lstm_cell/weights already exists, disallowed. Did you mean to set reuse=True in VarScope? Originally defined at:\n\n  File "/Users/xiaohuizhang/Documents/software/python/anaconda/lib/python2.7/site-packages/tensorflow/contrib/rnn/python/ops/core_rnn_cell_impl.py", line 747, in _linear\n    "weights", [total_arg_size, output_size], dtype=dtype)\n  File "/Users/xiaohuizhang/Documents/software/python/anaconda/lib/python2.7/site-packages/tensorflow/contrib/rnn/python/ops/core_rnn_cell_impl.py", line 179, in __call__\n    concat = _linear([inputs, h], 4 * self._num_units, True, scope=scope)\n  File "<ipython-input-5-5a82fdc53752>", line 20, in lstm\n    output_rnn,final_states=tf.nn.dynamic_rnn(cell, input_rnn,initial_state=init_state, dtype=tf.float32)  #output_rnn\u662f\u8bb0\u5f55lstm\u6bcf\u4e2a\u8f93\u51fa\u8282\u70b9\u7684\u7ed3\u679c\uff0cfinal_states\u662f\u6700\u540e\u4e00\u4e2acell\u7684\u7ed3\u679c\n', 783, 786, 'ordinal not in range(128)'))

**Comment by crystal-matrix** [comment]
为什么我训练后预测结果和您的不一样呢？

**Comment by crystal-tensor** [comment]
![qq 20170706142608](https://user-images.githubusercontent.com/29765585/27898153-2cf56c60-6257-11e7-89ae-346a748e206e.png)
为什么我训练后预测结果和您的不一样呢？

**Comment by crystal-tensor** [comment]
上面那个是重复训练2000次的结果，难道要10000次吗？

**Comment by crystal-tensor** [comment]
![qq 20170706170712](https://user-images.githubusercontent.com/29765585/27903918-97f3f840-626d-11e7-92c8-f19aae73af5b.png)
这个是训练10000次后的预测结果，跟您的完全不一样，怎么回事啊？

**Comment by csyfcc** [comment]
@crystal-matrix  你好，请问你是怎么debug得出来的结果？我程序连跑都跑不了，能分享下代码吗？

**Comment by crystal-tensor** [comment]
把预测和训练的代码分别跑就能出结果，先跑训练部分的代码，把预测的代码注释掉，跑出模型后再注释掉训练的代码，去掉预测代码的注释，然后运行就有结果了





在 2017-07-14 03:11:08，"csyfcc" <notifications@github.com> 写道：


@crystal-matrix 你好，请问你是怎么debug得出来的结果？我程序连跑都跑不了，能分享下代码吗？
